language: php

php:
- '7.2'
- '7.3'
- nightly

matrix:
  allow_failures:
    - php: nightly

install:
- composer install --prefer-dist

after_success:
- composer global require humbug/box:^3.5 --prefer-dist
- composer install --no-dev
- ~/.composer/vendor/bin/box build --no-interaction

deploy:
  # Deploy to Github Releases
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: KlWV2gyjoEwvX0Hy8ciAazg7mrUl7eVqEAIMOfOEHQWvSc9TyJMFo9jaR+IY22BcPoDuVR4cIZhlwwVWWE1XJQX1k6umyNvu+Ki9ovKC+1zN7cNeEFA2BPK40Cz2dOBgXB/Q3nmqi/NoLXJtc0T33Fnid1inUrxU+YETFZUSdrtHPMm3w8qDb2Sd4flgy10V8Emp6KAKje6cNNEinaGaUXlbVlR/DBWYqi8Np/umjO9P/ou60GuUvP+MoRrK7Y3fx0USple+jrq5gZXjytPx3uXRdwKW1m2A8LSSVD+WiprbTPWosyR4WcZCWwcnxmVx+DCT8sPk5WCDYfi47x9uwNTNTz1EPKNf3p1Nxo715IgrwxNYWxCOdjAgcpQaWmxxbnQOzmw/LE5s981VIlKblBBXFS1Ou0t26v7pwku1Q8RnNAnUfWZh+sFvs7HBsvXU3HRpMOP4sJImo0YmX8UjzNazRRNqT9cvTwFiTfWaksnqmluA/F/bEjzScF6WONqcFtr5Gtj3kRYeID09jesfcdT87eWLnCJXW6u5Hm8H/ikBHd0YovB0esRUOpDJxoiPpyhnCFkYCLZ6QGgSRa74swaaDgAl+c2/JCD5jHTdVFx+hm2Nk4+wYO5V2FzK8wRg2IvBM3/DF4YDpx5wGoQtvLHVW6kpJsUbyDVBM719FMg=
    file: msml.phar
    on:
      repo: spejder/msml
      tags: true
      php: '7.2'

  # Purge the releases badge to get the new release number in there
  - provider: script
    script: curl --silent -X PURGE https://camo.githubusercontent.com/629b33942e20acc0de5bf90146c115c8d948ee25/68747470733a2f2f6769746875622d72656c656173652d76657273696f6e2e6865726f6b756170702e636f6d2f6769746875622f7370656a6465722f6d736d6c2f72656c656173652e737667
    on:
      repo: spejder/msml
      tags: true
      php: '7.2'
